os: linux
dist: xenial
language: ruby
rvm:
- 2.7.0

script:
  - set -e # halt script on error
  - bundle exec jekyll build
  - bundle exec htmlproofer --http-status-ignore "999" --url-ignore "/https://twitter.com/intent/tweet?text=*/" ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
